webtalk_init -webtalk_dir E:/Uni_Year2_Labs/DDHDL/DDHDL_Assignment/DDHDL_FinalProject/DDHDL_FinalProject.sim/sim_1/behav/xsim/xsim.dir/Matrix_Multiplier_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Nov 28 19:33:47 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174238993_1777531742_210673935_605" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b7324af0-260a-4125-8922-328fcb5be000" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e6023d7d20e64012b0424a30a2cd947e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "215" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3192 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "25 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7800_KB" -context "xsim\\usage"
webtalk_transmit -clientid 217109328 -regid "174238993_1777531742_210673935_605" -xml E:/Uni_Year2_Labs/DDHDL/DDHDL_Assignment/DDHDL_FinalProject/DDHDL_FinalProject.sim/sim_1/behav/xsim/xsim.dir/Matrix_Multiplier_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/Uni_Year2_Labs/DDHDL/DDHDL_Assignment/DDHDL_FinalProject/DDHDL_FinalProject.sim/sim_1/behav/xsim/xsim.dir/Matrix_Multiplier_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/Uni_Year2_Labs/DDHDL/DDHDL_Assignment/DDHDL_FinalProject/DDHDL_FinalProject.sim/sim_1/behav/xsim/xsim.dir/Matrix_Multiplier_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
